
options_map = {
    "Arc":['Arc','ArcOptions','ArcIns'],
    "Circle":['Circle','CircleOptions','CircleIns'],
    "Group":['Group'],
    "destory":[],
    "discolorateBorder":[],
    "discolorateBorderTo":[],
    "discolorateFill":[],
    "discolorateFillTo":[],
    "Ellipse":['Ellipse','EllipseOptions','EllipseIns'],
    "fadeIn":[],
    "fadeOut":[],
    "fadeTo":[],
    "grow":[],
    "Image":['Image','ImageOptions'],
    "Line":['Line','LineOptions','LineIns'],
    "move":[],
    "moveTo":[],
    "MathFunction":[],
    "moveOnFunction":[],
    "moveOnPath":['Path','PathOptions','PathIns'],
    "NumberAxis":[],
    "NumberPlane":[],
    "PolarPlane":[],
    "Polygon":['Polygon','PolygonOptions','PolygonIns'],
    "Rect":['Rect','RectOptions','RectIns'],
    "rotate":[],
    "rotateTo":[],
    "scale":[],
    "scaleTo":[],
    "Tex":[],
    "Text":['Text','TextOptions','TextIns'],
    "TextUnit":['TextUnit'],
    "trace":[],
    "Video":['Video','VideoOptions'],
    "Webview":['Webview','WebviewOptions','WebviewIns'],
}

timingsFuctions_map = {
    "sine":['easeInSine', 'easeOutSine', 'easeInOutSine'],
    "quad":['easeInQuad', 'easeOutQuad', 'easeInOutQuad'],
    "cubic":['easeInCubic', 'easeOutCubic', 'easeInOutCubic'],
    "quart":['easeInQuart', 'easeOutQuart', 'easeInOutQuart'],
    "quint":['easeInQuint', 'easeOutQuint', 'easeInOutQuint'],
    "expo":['easeInExpo', 'easeOutExpo', 'easeInOutExpo'],
    "circ":['easeInCirc', 'easeOutCirc', 'easeInOutCirc'],
    "back":['easeInBack', 'easeOutBack', 'easeInOutBack'],
    "elastic":['easeInElastic', 'easeOutElastic', 'easeInOutElastic'],
    "bounce":['easeBounce']
}

animation_map = {
    'discolorate':['offset'],
    'discolorateTo':['to'],
    'discolorateBorder':['offset'],
    'discolorateBorderTo':['to'],
    'discolorateFill':['offset'],
    'discolorateFillTo':['to'],
    'move':['offsetX','offsetY'],
    'grow':['offsetX','offsetY'],
    'moveTo':['toX','toY'],
    # 'scale':['offsetX','offsetY'],
    # 'scaleTo':['toX','toY'],
    'rotate':['offset'],
    'rotateTo':['to'],
    'fadeTo':['to'],
    'fadeIn':[],
    'fadeOut':[],
    'zoomTo':['toX','toY'],
    'zoomIn':[],
    'zoomOut':[],
    # 'moveOnPath':['path'],
    # 'moveOnFunction':['path'],
    # 'destory':[],
    # 'trace':[],
    # 'traceFill':[],

}